<?php

/**
 * Représente un contrôleur / modèle de page web
 */
class Controller {
    /**
     * Data generated by model
     *
     * @var array
     */
    protected $data; // Mixed data registred by the page
    /**
     * Title of the page
     *
     * @var string|null
     */
    protected $page_title; // Page title;  If null: no title
    /**
     * View function to call
     *
     * @var callable|null
     */
    protected $view; // Callback function to call on invoke()

    /**
     * Initialise le controlleur avec les données (modèle).
     *
     * @param array $data
     * @param string|null $title
     */
    public function __construct(array $data = [], ?string $title = null) {
        $this->data = $data;
        if ($title) {
            $this->page_title = $title;
        }
    }

    protected $loaded = false;

    /**
     * Indique des informations de debug
     *
     * @return array
     */
    public function __debugInfo() : array {
        return [
            'data' => $this->data,
            'function_view' => $this->view,
            'title' => $this->page_title,
            'displayed_view_function' => $this->loaded
        ];
    }
    
    /**
     * Appelle la fonction de vue avec les données générées par le modèle.
     *
     * @return void
     */
    public function __invoke() {
        if ($this->loaded) {
            throw new RuntimeException("View function has been called twice");
        }

        if ($this->view === null) {
            throw new UnexpectedValueException("No view function defined");
        }

        // Appel de la fonction contenue dans view avec le contrôleur en paramètre
        ($this->view)($this);

        $this->loaded = true;
    }

    public function setTitle(?string $title) : ?string {
        $this->page_title = $title;
        return $this->page_title;
    }

    public function getTitle() : ?string {
        return $this->page_title;
    }

    public function setViewFunction(callable $func_name) : callable {
        $this->view = $func_name;
        return $this->view;
    }

    public function getData() : array {
        return $this->data;
    }

    public function setData(array $data) : array {
        $this->data = $data;
        return $this->data;
    }
}
